### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by Vinlock** [adrianlee44/atom-aligner-python#1]
**Atom Version**: 1.1.0
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [aligner-python](https://github.com/adrianlee44/atom-aligner-python) package, v1.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'detach' of undefined

```
At /C:/Users/dakfi/.atom/packages/php-class-tree/lib/php-class-tree.coffee:44

TypeError: Cannot read property 'detach' of undefined
  at PhpClassTree.detach (C:\Users\dakfi\.atom\packages\php-class-tree\lib\php-class-tree.coffee:34:14)
  at Function.Main.getPhpClassTreeByEditor (C:\Users\dakfi\.atom\packages\php-class-tree\lib\php-class-tree.coffee:245:17)
  at C:\Users\dakfi\.atom\packages\php-class-tree\lib\php-class-tree.coffee:212:22
  at Emitter.module.exports.Emitter.emit (C:\Users\dakfi\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at C:\Users\dakfi\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane-container.js:333:27
  at Emitter.module.exports.Emitter.emit (C:\Users\dakfi\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\dakfi\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:247:22)
  at Pane.module.exports.Pane.activateItem (C:\Users\dakfi\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:311:21)
  at Pane.module.exports.Pane.activateItemAtIndex (C:\Users\dakfi\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:305:19)
  at Pane.module.exports.Pane.activatePreviousItem (C:\Users\dakfi\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:276:21)
  at Pane.module.exports.Pane.removeItem (C:\Users\dakfi\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:386:16)
  at Pane.module.exports.Pane.destroyItem (C:\Users\dakfi\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:448:16)
  at HTMLDivElement.<anonymous> (C:\Users\dakfi\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:236:22)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\dakfi\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-ul.elemData.handle (C:\Users\dakfi\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -1:57.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:57.8.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:57.6.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:57.6.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:57.6.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:57 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:57 snippets:expand (atom-text-editor.editor.is-focused)
     -1:57 editor:indent (atom-text-editor.editor.is-focused)
     -1:55 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -1:55 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -1:53.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:25.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:24.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:24.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:24.8.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -1:24.5.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "drunken-php",
      "php-class-tree",
      "atom-autocomplete-php",
      "aligner-python"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-php, v0.3.7
autocomplete-python, v0.9.4

# Dev
No dev packages
```

**Comment by adrianlee44** [comment]
This is an error from `php-class-tree` package.
